In [6]:
import pandas as pd
import numpy as np
import os

In [33]:
# Take the parent dirname for the raw data
parentdir = os.path.dirname(os.path.dirname(os.path.abspath("__file__")))
rawdir = os.path.join(parentdir,"raw_data")
rawdir

'/Users/nicolashenriquezurzua/code/AmaurySALLES/projectwind/raw_data'

In [64]:
os.path.join(rawdir,"A01.csv")

'/Users/nicolashenriquezurzua/code/AmaurySALLES/projectwind/raw_data/A01.csv'

In [36]:
def concatenate_df():
    # Take the parent dirname for the raw data
    parentdir = os.path.dirname(os.path.dirname(os.path.abspath("__file__")))
    rawdir = os.path.join(parentdir,"raw_data")
    
    # init global DF
    globalDF = pd.read_csv(os.path.join(rawdir,"A01.csv"))
    globalDF["Turbine_id"] = 1
    
    # loop over the CSVs
    for i in range(2,26):
    # CSV file name    
        if i <10:
            file="A0"+str(i)+".csv"
        else:
            file="A"+str(i)+".csv"
        df = pd.read_csv(os.path.join(rawdir,file))
        # add an ID for each turbine
        df["Turbine_id"] = i
        
        #concatenate df
        globalDF = pd.concat((globalDF,df),ignore_index=True)
    return globalDF

In [60]:
a=concatenate_df()
a

,Fecha,Desalineación Nacelle y Dirección de Viento Media 10M\n(°),Media de Potencia Activa 10M\n(kW),Posición Nacelle Media 10M\n(°),Velocidad Rotor Media 10M\n(rpm),Velocidad Viento Media 10M\n(m/s),Ángulo Pitch Media 10M\n(°),Turbine_id
0,01/05/19 00:00,358.07,1357.58,194.00,11.94,8.80,-0.79,1
1,01/05/19 00:10,2.63,1252.87,194.00,11.58,8.13,-0.42,1
2,01/05/19 00:20,1.85,1661.33,194.00,12.60,9.09,-0.36,1
3,01/05/19 00:30,355.89,1863.22,194.00,12.87,10.15,0.64,1
4,01/05/19 00:40,358.16,1942.12,194.00,12.97,10.04,0.42,1
...,...,...,...,...,...,...,...,...
3084070,30/09/21 23:10,5.90,16.59,96.64,8.19,3.41,2.98,25
3084071,30/09/21 23:20,4.21,94.53,113.00,8.19,3.91,2.49,25
3084072,30/09/21 23:30,5.60,138.04,113.00,8.19,4.35,1.92,25
3084073,30/09/21 23:40,355.48,59.68,113.00,8.20,4.10,2.29,25
3084074,30/09/21 23:50,354.71,37.11,113.00,8.20,3.86,2.57,25

In [61]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
a.describe()

,Desalineación Nacelle y Dirección de Viento Media 10M\n(°),Media de Potencia Activa 10M\n(kW),Posición Nacelle Media 10M\n(°),Velocidad Rotor Media 10M\n(rpm),Velocidad Viento Media 10M\n(m/s),Ángulo Pitch Media 10M\n(°),Turbine_id
count,3084050.00,3084075.00,3083950.00,3084025.00,3084050.00,3084000.00,3084075.00
mean,168.44,731.86,145.57,9.14,6.49,6.57,13.00
std,173.32,654.60,52.72,3.16,2.61,19.87,7.21
min,0.00,-27.57,0.00,0.00,0.14,-1.00,1.00
25%,2.75,161.79,114.00,8.19,4.70,-0.51,7.00
50%,25.67,564.36,140.00,9.14,6.43,0.10,13.00
75%,357.09,1179.80,180.00,11.46,8.26,2.44,19.00
max,360.00,2119.69,360.00,13.13,20.55,87.30,25.00

In [48]:
a["delta"] = abs(a['Desalineación Nacelle y Dirección de Viento Media 10M\n(°)']-a['Ángulo Pitch Media 10M\n(°)'])

In [49]:
a.columns

Index(['Fecha', 'Desalineación Nacelle y Dirección de Viento Media 10M\n(°)',
       'Media de Potencia Activa 10M\n(kW)', 'Posición Nacelle Media 10M\n(°)',
       'Velocidad Rotor Media 10M\n(rpm)', 'Velocidad Viento Media 10M\n(m/s)',
       'Ángulo Pitch Media 10M\n(°)', 'Turbine_id', 'delta'],
      dtype='object')

In [50]:
a

,Fecha,Desalineación Nacelle y Dirección de Viento Media 10M\n(°),Media de Potencia Activa 10M\n(kW),Posición Nacelle Media 10M\n(°),Velocidad Rotor Media 10M\n(rpm),Velocidad Viento Media 10M\n(m/s),Ángulo Pitch Media 10M\n(°),Turbine_id,delta
0,01/05/19 00:00,358.07,1357.58,194.00,11.94,8.80,-0.79,1,358.87
1,01/05/19 00:10,2.63,1252.87,194.00,11.58,8.13,-0.42,1,3.05
2,01/05/19 00:20,1.85,1661.33,194.00,12.60,9.09,-0.36,1,2.21
3,01/05/19 00:30,355.89,1863.22,194.00,12.87,10.15,0.64,1,355.25
4,01/05/19 00:40,358.16,1942.12,194.00,12.97,10.04,0.42,1,357.74
...,...,...,...,...,...,...,...,...,...
3084070,30/09/21 23:10,5.90,16.59,96.64,8.19,3.41,2.98,25,2.93
3084071,30/09/21 23:20,4.21,94.53,113.00,8.19,3.91,2.49,25,1.72
3084072,30/09/21 23:30,5.60,138.04,113.00,8.19,4.35,1.92,25,3.68
3084073,30/09/21 23:40,355.48,59.68,113.00,8.20,4.10,2.29,25,353.19
3084074,30/09/21 23:50,354.71,37.11,113.00,8.20,3.86,2.57,25,352.13

In [62]:
a.isna().sum()

Fecha                                                           0
Desalineación Nacelle y Dirección de Viento Media 10M\n(°)     25
Media de Potencia Activa 10M\n(kW)                              0
Posición Nacelle Media 10M\n(°)                               125
Velocidad Rotor Media 10M\n(rpm)                               50
Velocidad Viento Media 10M\n(m/s)                              25
Ángulo Pitch Media 10M\n(°)                                    75
Turbine_id                                                      0
dtype: int64

A01.csv